/*ABAIXO AS FORMAS DE FILTRAR VALORES NULOS DE UMA TABELA*/
SELECT NOMEDOCAMPO1, NOMEDOCAMPO2 FROM NOMEDATABELA WHERE NOMEDOCAMPO = NULL;

SELECT NOMEDOCAMPO1, NOMEDOCAMPO2 FROM NOMEDATABELA WHERE NOMEDOCAMPO IS NULL;

SELECT NOMEDOCAMPO1, NOMEDOCAMPO2 FROM NOMEDATABELA WHERE NOMEDOCAMPO IS NOT NULL;