<?php
	echo phpversion();

	/*A CONEXÃO COM BANCO DE DADOS ATRAVÉS DE PDO É REALIZADA SEGUINDO OS PADRÕES DA ORIENTAÇÃO
	A OBJETOS*/

	/*INSTANCIAÇÃO DO OBJETO PDO - A FUNÇÃO PDO RECEBE COMO ARGUMENTOS O CAMINHO DO BANCO DE DADOS DENTRO
	DO SISTEMA*/

